twig:
    file_name_pattern: '*.twig'
    cache: false
    globals:
        app_name: '%env(APP_NAME)%'
        shipping_charge:
            standard: 30000
            express: 70000

when@test:
    twig:
        strict_variables: true
